replicaCount: 1
image:
  repository: ghcr.io/shareify-project/shareify-notification-service
  pullPolicy: Always
  tag: "18a0dbb"
imagePullSecrets:
  - name: ghcr-secret
env:
  databasePath: "/app/data/notification.db"
  smtpPassword: "change-me-password"
service:
  type: ClusterIP
  port: 800000
persistence:
  enabled: true
  storageClass: "nfs-client"
  size: 1Gi
  mountPath: /app/data
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 16Mi

config: {}
secrets: {}



