apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-config
data:
  DATABASE_PATH: {{ .Values.env.databasePath | quote }}
  SMTP_SERVER: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "muvvaalaakash@gmail.com"
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secret
type: Opaque
data:
  SMTP_PASSWORD: {{ .Values.env.smtpPassword | b64enc | quote }}
